### PR TITLE
- added ability to display Dropdowns instead of checkboxes

### PR DESCRIPTION
**Pull request by Restrikted**
- add new static Builder method formats: new[ClassName] and new[ClassName]Builder
- Selection of static Builder method names is now a drop down instead of checkboxes
- added option to select where the generated Builder method is set (inside parent class or generated Builder class)

### CODE REVIEW

**Comment by Restrikted** [comment]
Hi there

On the projects I'm working on, we have made some agreements on Builder method names and such.
For us the developers, it caused multiple manual actions, reducing productivity.
We thought it would be handy to add these options to your builder.
Have a look, share your thoughts if I can improve anything.
I hope this PR can make it through :-)

**Comment by analytically** [comment]
screenshot 2022-07-29 at 12 01 10@2x

**Comment by analytically** [comment]
@Restrikted ^^

**Comment by Restrikted** [comment]
I'm uncertain what is causing these warnings... I'm not finding any reference for a Builder for the SelectorOption (which indeed makes no sense). 
I'm not receiving the warning when I run the verifier plugin locally.
Any idea what can cause this?

**Comment by analytically** [comment]
Maybe the lack of a Builder constructor without arguments? It's got something to do with serialisation?

**Comment by Restrikted** [comment]
Could you give that a shot? Since the plugin verifier is not giving an error on my computer :-(

**Comment by analytically** [comment]
Hmm will need to revert this, can't find the issue

**Comment by analytically** [comment]
@Restrikted I've released 1.3.0 with your changes but they don't seem to work, can you debug?

**Pull request merged**
